### ISSUE TITLE
Doc enterprise customer support process

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-handbook#108]
Document process for large, strategic accounts to engage with Mattermost on pre-release server

- Invitation process & expectations on pre-release, naming convention, Jira query
- Process to select codename
- How PMs are assigned, and noted in channel header 
- Escalation process of issue reports, e.g. basic repro to Ops, advanced repro to QA, confirmed repro to PM to prioritize,

**Comment by justinegeffen** [comment]
@sadohert, this is an old issue but one that I'd like to confirm has been addressed or actioned before I close it. Thank you! :)

**Comment by sadohert** [comment]
Hey @justinegeffen - I think this has generally been addressed.  A few things have changed since 2017 (you could probably replace mention of "PM" with "CSM" instead).  We haven't done the "codename" thing with many customers (I've only done it with one so far)... I think we have this covered for when it comes up.

I think you're okay to close this.
