### ISSUE TITLE
Document new "1: SME Review" label

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-handbook#80]
Created a new "1: SME Review" label when a PR requires review by a subject matter expert.

Labels are currently documented at https://developers.mattermost.com/contribute/getting-started/labels/

This replaces "1: PM Review" and "2: Dev Review" labels used in our other documentation repos, given a "PM" or "Dev" review isn't applicable for the handbook.

**Comment by justinegeffen** [comment]
This is a great idea. Apparently GitHub doesn't do workflows connected to labels so I was wondering if department SME labels might work well? So, "SME - HR", "SME - G&A" etc?

**Comment by jasonblais** [comment]
Interesting idea! Would the department-specific SME labels bring more clarity on who the review is requested from?

**Comment by justinegeffen** [comment]
Good question. One option is that each new issue has the department name in the title (if possible) so there's an obvious indication of which department it's for (e.g. "HR: Update recruiting doc") and then it's up to the various departments to keep an eye on the handbook repo for labels pertaining to their team in general? Not sure if the former cancels the need for the latter out though?

**Comment by jasonblais** [comment]
@justinegeffen Got it - the "1: SME Review" was more thought for PM reviews, but having department-specific labels for issues also makes sense. We could do something like in the server repo with different areas labeled as `Area/XXX`. What do you think?

![image](https://user-images.githubusercontent.com/13119842/76754704-ef6e7d00-6758-11ea-803c-f0cbcde71b36.png)

**Comment by justinegeffen** [comment]
Sorry about the delay on this - I completely dropped the ball.

That's what I was thinking about. A use case that I have now is that I am transferring Handbook-related issues from the docs repo to the handbook repo. It would be helpful to be able to label them as "HR", "Finance", "BizOps" so that for example, Natalie and Tim could easily see which issues apply to their current project and not have to open each one individually. It would also help with SME review as the respective teams could see what type of SME is needed without needing to be tagged. 

If that works, we do need to decide on the label names - not everything is distinctly HR or BizOps but that can be discussed if this suggestion is viable.

**Comment by jasonblais** [comment]
@justinegeffen :+1: 

Created a few labels for different areas to get started - happy to iterate on them as we start using the labels
![image](https://user-images.githubusercontent.com/13119842/78722419-71386d00-78f7-11ea-881b-342bb2f52f74.png)

**Comment by jasonblais** [comment]
I changed the labels to `Department/XXX` after posting -- department seemed more clear than `Area`. Though I'm 0/5 on the exact labels, we can always change it to something more clear
